/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_abe_com_android_activity_jni_JNIActivity */

#ifndef _Included_example_abe_com_android_activity_jni_JNIActivity
#define _Included_example_abe_com_android_activity_jni_JNIActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_abe_com_android_activity_jni_JNIActivity
 * Method:    getHelloContent
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_example_abe_com_android_activity_jni_JNIActivity_getHelloContent
  (JNIEnv *, jobject);

/*
 * Class:     example_abe_com_android_activity_jni_JNIActivity
 * Method:    showHelloContent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example_abe_com_android_activity_jni_JNIActivity_showHelloContent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
